### ISSUE TITLE
m_offset_model.predict_new 

### ISSUE THREAD

**Issue by enjieli** [david-cortes/cmfrec#8]
Hi David,

Thanks for developing such a wonderful package. 

I am using your offset model to predict ratings for a new item using item side info , but I just cannot get the OMF_explicit.predict_new function to work. 

I have created the train test dataset based on your notebook. For ratings_test1, my 
```python
m_offset_model.predict(ratings_test1.UserId, ratings_test1.ItemId)
```
function works, and i got decent RMSE and R squared : 0.939. But when i did 

```python
 m_offset_model.predict_new(ratings_test2.UserId, item_attr_test.loc[ratings_test2.ItemId])
```

 I got an error: 
```
ValueError                                Traceback (most recent call last)
<ipython-input-14-7a852e669d0c> in <module>
      2 ### offset model
      3 pred_offset = m_offset_model.predict_new(ratings_test2.UserId,
----> 4                                        item_attr_test.loc[ratings_test2.ItemId])
      5 print("RMSE type 2 offset model: %.3f [rho: %.3f]" %
      6       (mean_squared_error(ratings_test2.Rating,

~/opt/anaconda3/envs/recommender/lib/python3.7/site-packages/cmfrec/__init__.py in predict_new(self, user, I)
   3699             Predicted ratings for the requested user-item combinations.
   3700         """
-> 3701         B = self._factors_cold_multiple(U=I, is_I=True)
   3702         return self._predict_new(user, B)
   3703 

~/opt/anaconda3/envs/recommender/lib/python3.7/site-packages/cmfrec/__init__.py in _factors_cold_multiple(self, U, is_I)
   3624         if Mat.shape[0] == 0:
   3625             msg  = "Can only use this method when fitting the model to %s side info."
-> 3626             raise ValueError(msg % infoname)
   3627         if (U is not None) and (len(U.shape) != 2):
   3628             raise ValueError("'%s' must be 2-dimensional." % letter)

ValueError: Can only use this method when fitting the model to item side info.
```

The same ratings_test2 dataset have worked fine on CMF_explicit models predict_new function with various combination of w_main and w_weight.  I am wondering does OMF_explicit predict_new require a different type of data structure? Any ideas how to fix this?
Thank you so so much!

Jane

**Comment by david-cortes** [comment]
Hmm, that's weird. Are you sure you passed the `I` data to `fit`? Note that the order of the arguments is not the same between `CMF_explicit` and `OMF_explicit` as the first one has more options.

Does the model have a non-empty matrix `D_`? (this is under `m_offset_model.D_`)

Also could you try the following examples:
```python
import numpy as np, pandas as pd
from cmfrec import OMF_explicit

n_users = 4
n_items = 5
n_ratings = 10
n_user_attr = 4
n_item_attr = 5
k = 3


np.random.seed(1)
ratings = pd.DataFrame({
    "UserId" : np.random.randint(n_users, size=n_ratings),
    "ItemId" : np.random.randint(n_items, size=n_ratings),
    "Rating" : np.random.normal(loc=3., size=n_ratings)
})
item_info = pd.DataFrame(np.random.normal(size = (n_items, n_item_attr)))
item_info["ItemId"] = np.arange(n_items)
```
```python
model = OMF_explicit()
model.fit(ratings, I=item_info)

users_pred = np.random.randint(n_users, size=3)
items_pred = item_info.drop("ItemId", axis=1).loc[np.random.randint(n_items, size=3)]

model.predict_new(user=users_pred, I=items_pred)
```
```python
from scipy.sparse import coo_matrix
ratings_COO = coo_matrix((ratings.Rating, (ratings.UserId, ratings.ItemId)))
model = OMF_explicit()
model.fit(X=ratings_COO, I=item_info.drop("ItemId", axis=1))
model.predict_new(user=users_pred, I=items_pred)
```

**Comment by enjieli** [comment]
Hi David, 

Thank you so much for your quick response. You are right, I did not pass the right item_attr_train in mode fit. I apologize for my carelessness. The sample code you sent are working fine. 

Now I am trying to tune the OMF model and having a hard time to make the model converge. I have set the maxiter=0, but I am not sure what is the optimal way of tuning Lambda. I have scaled the ratings using MinMaxScaler() before passing it to the model. 

Here is my code:
```python
m_offset_model = OMF_explicit(k=40, user_bias=True, item_bias=True,
                               method='lbfgs', maxiter=0,
                               lambda_=[100, 100,1.e-1, 100, 100, 1000])\
                .fit(X=ratings_train, I=item_attr_train)
```
In your notebook you mentioned that lower lambda will likely cause overfit while larger lambda will likely cause underfit. Could you please elaborate a bit more on how each of the six lambda will affect model fitting in the case of OMF with item_side_info? and and any techniques to find the optimal lambda?  thanks!

**Comment by enjieli** [comment]
also, I forgot to mention that when I use the default lamdba value =10:

```python
m_offset_model = OMF_explicit(k=40, user_bias=True, item_bias=True,
                               method='lbfgs', maxiter=0)\
                              .fit(X=ratings_train, I=item_attr_train)
```
model is pretty fast to converge.  but my R^2 for ratings_test2  is about 0.622. that's why I am trying to play with different lambda to see whether I can get the R^2 up. Any other method to increase model accuracy? 

Thank you so so much!!!

**Comment by david-cortes** [comment]
The effect of varying `lambda_` is the same as in linear regression: larger values will make the coefficients shrink towards zero, and thus will make the predictions overall be less variable around the average rating. So e.g. if you set a large `lambda_` for `D_`, you’ll make the attribute coefficients play a smaller role in the final formula, making it comparatively less important than the ratings info. In addition, here you also have the issue that the coefficients for some things show up more frequently in the data (e.g. the item bias for a given item probably affects many more observations than some user coefficients), so the ones that affect more entries are penalized less by the same regularization.

As for how to tune it, it’s the same as for other models: try different values through e.g. grid search, randomized search, gaussian process optimization, etc. and pick the one giving the best evaluation metric for your use case (e.g. NDCG, RMSE, or some custom metric measuring e.g. serendipity or other aspects). Here you also have the additional clue that if it takes too many iterations to converge, some of the values might be too small.

Now in this case, since you’re dealing with censored data (incomplete explicit feedback), you likely want to be careful with your choice of metric instead of guiding all decisions by RMSE/R^2, otherwise you’ll find that sorting items by average rating produces low RMSE but recommends as top-N items rated by 1 or 2 people only (optimal for R^2 is to set zero `lambda_` to the intercepts). There’s quite a lot written about evaluating recommender systems, but basically you want to balance either a regression error or ranking goodness under the observed entries with other properties of the ranking when including unseen items.

As a shorthand, if you’re going to compare only one class of model (e.g. only `OMF_explicit`), you can try different single-valued `lambda_` in decreasing order, check if the rankings look personalized, and stop if you see that they recommend too uncommon items or take too long to fit.

**Comment by david-cortes** [comment]
EDIT: oh sorry I was thinking about `CMF_explicit` and general tuning. If you want to tune the `lambda_`s in `OMF_explicit` for `predict_new`, basically just do a grid search or GPO with e.g. RMSE as metric in your data for old_users-new_items, with a few values (I'd recommend: `1e+2, 5e+2, 1e+1, 5e+1, 1e0, 1e-1, `), keeping in mind:
* You likely want a higher regularization for `B_` than for `D_`.
* You might not want to include item biases, or might want to set a very high regularization for them.
* You definitely want to use early stopping (e.g. `maxiter=2000`) for quickly comparing values, then later fit a model with larger maxiter.
* You'll likely want to adjust regularization according to number of feeatures used.

**Comment by enjieli** [comment]
Thank you for your thorough explanation, David! It makes a lot of sense now!
I will definitely play with other evaluation metrics to get a better sense of model performance.

**Comment by enjieli** [comment]
Hi David, I noticed that if I accidentally input a new user in the `OMF_explicit.predict_new` function, the kernel will crash without any warning. Perhaps a warning, "UserID is not in the training set" would be helpful. It took me a second to figure out why my model was constantly crashing.... finally made some progress on model tuning! thank you so much!!!

**Comment by david-cortes** [comment]
Thanks for the bug report. Fixed now.
